Fix failing tests
- Fix running of fortran 'test-suite' executables
- Makefile tweaks

diff --git a/Examples/Makefile.in b/Examples/Makefile.in
--- a/Examples/Makefile.in
+++ b/Examples/Makefile.in
@@ -2029,7 +2029,7 @@ FORTRAN = @FORTRAN@
 FORTRANCFLAGS =
 FORTRAN_RUNME = $(RUNME)
 FORTRAN_CSUMMARY = "summary-c.txt"
-FORTRAN_SUMMARY = "summary.txt"
+FORTRAN_CXXSUMMARY = "summary-cxx.txt"
 FOBJ = $(INTERFACE:.i=_fort.@OBJEXT@)
 
 ifneq (,$(SRCDIR))
@@ -2049,20 +2049,18 @@ fortran: $(SRCDIR_SRCS)
 	$(TCLLDSHARED) $(CFLAGS) $(LDFLAGS) $(OBJS) $(IOBJS) $(FOBJ) $(TCL_DLNK) \
 			$(LIBS) -o $(LIBPREFIX)$(TARGET)$(TCL_SO) \
 		|| (echo "$(TARGET)|failed to link" >> $(FORTRAN_CSUMMARY) && exit 1)
-	echo "$(TARGET)|passed" >> $(FORTRAN_CSUMMARY)
 
 fortran_cpp: $(SRCDIR_SRCS)
 	$(SWIG) -fortran -c++ $(SWIGOPT) -o $(ICXXSRCS) $(INTERFACEPATH) \
-		|| (echo "$(TARGET)|failed to run swig" >> $(FORTRAN_SUMMARY) && exit 1)
+		|| (echo "$(TARGET)|failed to run swig" >> $(FORTRAN_CXXSUMMARY) && exit 1)
 	$(CXX) -c $(CCSHARED) $(CPPFLAGS) $(CXXFLAGS) $(FORTRANCFLAGS) \
 			$(SRCDIR_SRCS) $(SRCDIR_CXXSRCS) $(ICXXSRCS) $(INCLUDES) \
-		|| (echo "$(TARGET)|failed to compile wrapper" >> $(FORTRAN_SUMMARY) && exit 1)
+		|| (echo "$(TARGET)|failed to compile wrapper" >> $(FORTRAN_CXXSUMMARY) && exit 1)
 	$(FORTRAN) -c $(TARGET).f90 -o $(FOBJ) \
-		|| (echo "$(TARGET)|failed to compile fortran" >> $(FORTRAN_SUMMARY) && exit 1)
+		|| (echo "$(TARGET)|failed to compile fortran" >> $(FORTRAN_CXXSUMMARY) && exit 1)
 	$(TCLCXXSHARED) $(CXXFLAGS) $(LDFLAGS) $(OBJS) $(IOBJS) $(FOBJ) $(TCL_DLNK) \
 			$(LIBS) $(CXX_DLLIBS) -o $(LIBPREFIX)$(TARGET)$(TCL_SO) \
-		|| (echo "$(TARGET)|failed to link" >> $(FORTRAN_SUMMARY) && exit 1)
-	echo "$(TARGET)|passed" >> $(FORTRAN_SUMMARY)
+		|| (echo "$(TARGET)|failed to link" >> $(FORTRAN_CXXSUMMARY) && exit 1)
 
 fortran_run: $(SRCDIR_SRCS)
 	env LD_LIBRARY_PATH=$$PWD $(RUNTOOL) ./$(RUNME).exe $(RUNPIPE)
diff --git a/Examples/test-suite/fortran/Makefile.in b/Examples/test-suite/fortran/Makefile.in
--- a/Examples/test-suite/fortran/Makefile.in
+++ b/Examples/test-suite/fortran/Makefile.in
@@ -5,7 +5,6 @@
 LANGUAGE	= fortran
 FORTRAN		= @FORTRAN@
 FC      	= @FC@
-host		= @host@
 SCRIPTSUFFIX= _runme.f90
 
 FORTRANOBJEXT = o
@@ -21,32 +20,39 @@ include $(srcdir)/failing-cpp-tests.mk
 include $(srcdir)/failing-c-tests.mk
 include $(srcdir)/../common.mk
 
+FORTRAN_CSUMMARY = "summary-c.txt"
+FORTRAN_CXXSUMMARY = "summary-cxx.txt"
+
 .SUFFIXES: .cpptest .ctest .multicpptest
 
 # Rules for the different types of tests
 %.cpptest:
 	$(setup)
 	+$(swig_and_compile_cpp)
-	$(run_testcase_cpp)
+	$(run_testcase)
+	echo "$(TARGET)|passed" >> $(FORTRAN_CXXSUMMARY)
 
 %.ctest:
 	$(setup)
 	+$(swig_and_compile_c)
-	$(run_testcase_cpp)
+	$(run_testcase)
+	echo "$(TARGET)|passed" >> $(FORTRAN_CSUMMARY)
 
 %.multicpptest:
 	$(setup)
 	+$(swig_and_compile_multi_cpp)
-	$(run_testcase_cpp)
+	$(run_testcase)
+	echo "$(TARGET)|passed" >> $(FORTRAN_CXXSUMMARY)
 
 # Runs the testcase.
-run_testcase_cpp = \
-	if test -f $(SCRIPTDIR)/$(SCRIPTPREFIX)$*$(SCRIPTSUFFIX); then \
-	    $(COMPILETOOL) $(FORTRAN) $*.f90 -c; \
-	    $(COMPILETOOL) $(FORTRAN) $(SCRIPTDIR)/$(SCRIPTPREFIX)$*$(SCRIPTSUFFIX) -c; \
-	    $(COMPILETOOL) $(FORTRAN) -o $*_runme.exe $(SCRIPTPREFIX)$*.@OBJEXT@ $(SCRIPTPREFIX)$*_runme.@OBJEXT@ \
-			$(LIBPREFIX)$*$(TCL_SO); \
-	  env LD_LIBRARY_PATH=.:$$LD_LIBRARY_PATH $(RUNTOOL) ./$*_runme.exe; \
+run_testcase = \
+	if [ -f $(SCRIPTDIR)/$(SCRIPTPREFIX)$*$(SCRIPTSUFFIX) ]; then \
+	  $(COMPILETOOL) $(FORTRAN) $(SCRIPTDIR)/$(SCRIPTPREFIX)$*$(SCRIPTSUFFIX) -c \
+		|| (echo "$*|failed to build test" >> $(FORTRAN_CSUMMARY) && exit 1); \
+	  $(COMPILETOOL) $(FORTRAN) -o $*_runme.exe $(SCRIPTPREFIX)$*_runme.@OBJEXT@ $(LIBPREFIX)$*$(TCL_SO) \
+		|| (echo "$*|failed to link test" >> $(FORTRAN_CSUMMARY) && exit 1); \
+      env LD_LIBRARY_PATH=.:$$LD_LIBRARY_PATH $(RUNTOOL) ./$*_runme.exe \
+		|| (echo "$*|failed to run test" >> $(FORTRAN_CSUMMARY) && exit 1) \
 	fi
 
 %.clean:
